# backend/catalog-service/cloudbuild.yaml
# CI/CD para Catalog Service en Google Cloud

steps:
  # STEP 1: Build de la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/catalog-service:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/catalog-service:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'backend/catalog-service'

  # STEP 2: Push de la imagen a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/catalog-service:$COMMIT_SHA'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/catalog-service:latest'
    waitFor: ['build-image']

  # STEP 3: Deploy a Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    args:
      - 'run'
      - 'deploy'
      - 'catalog-service'
      - '--image=gcr.io/$PROJECT_ID/catalog-service:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300'
      - '--port=8080'
      - '--set-env-vars=NODE_ENV=production,PORT=8080,DB_USER=musicstreamdb,DB_PASSWORD=Aa1005312807$,DB_NAME=musicstream_db,DB_PORT=5432,INSTANCE_CONNECTION_NAME=musicstreamlite:us-central1:musicstreamlite-db,GCP_PROJECT_ID=$PROJECT_ID,GCS_BUCKET=music-stream-lite-bucket'
    waitFor: ['push-image']

  # STEP 4: Health Check post-deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'health-check'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$(gcloud run services describe catalog-service \
          --region=us-central1 \
          --format='value(status.url)')
        echo "Service URL: $SERVICE_URL"
        sleep 10
        curl -f "$SERVICE_URL/health" || exit 1
    waitFor: ['deploy-cloud-run']

images:
  - 'gcr.io/$PROJECT_ID/catalog-service:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/catalog-service:latest'

timeout: 900s

options:
  machineType: 'N1_HIGHCPU_4'
  logging: CLOUD_LOGGING_ONLY